### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Adobe-Android** [darthbatman/pcpartpicker#1]
Would you consider adding config options to the CPU and Motherboard? It would also be useful to have the socket type property on the CPU.

**Comment by darthbatman** [comment]
What do you mean by "config options"?

**Comment by Adobe-Android** [comment]
Like what you did in your test.js. I noticed it was already set up under your getMemory function.

**Comment by Adobe-Android** [comment]
Here's an example 
`let memorySortOptions = {
  "size": ["16GB (2x8GB)"],
  "speed": ["DDR4-3733"]
};`

**Comment by darthbatman** [comment]
I have added socket sort options for the getCPUs() and getMotherboards()

**Comment by Adobe-Android** [comment]
Thank you very much!! I really appreciate this and I'll keep you updated on
my project if you like.
